config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('todoapp.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/urls.py
from django.urls import path
from .views import index,  single, create, delete

urlpatterns = [
    path('', index, name='index'),
    path('edit/<int:pk>/', single, name='single'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('create/', create, name='create'),
]

todoapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()

STATUS = (
    (0, _('New')),
    (1, _('Process')),
    (2, _('Complated')),
    (3, _('Cancelled')),
)


class Todo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Logo(models.Model):
     image = models.ImageField()
            

todoapp/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'title ...'
        })
        self.fields['content'].widget.attrs.update({
            'class': 'form-control',
            'rows': '3',
            'placeholder': 'content ...'
        })
        self.fields['status'].widget.attrs.update({
            'class': 'form-control',
        })

    class Meta:
        model = Todo
        fields = '__all__'
        exclude = ['author']

todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TodoForm
from .models import Todo, Logo
from django.contrib import messages


@login_required
def index(request):
    user = request.user
    todos = Todo.objects.filter(author=user).order_by('-updated_at')
    q = request.GET.get('q')
    if q:
        todos = todos.filter(status__exact=int(q))

    ctx = {
        'todos': todos,
    }
    return render(request, 'index.html', ctx)


@login_required
def single(request, pk):
    todo = Todo.objects.get(id=pk)
    form = TodoForm(request.POST or None, instance=todo)

    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = request.user
        obj.save()
        messages.success(request, 'successfully updated')
        return redirect('/')
    ctx = {
        'form': form
    }
    return render(request, 'single.html', ctx)


@login_required
def create(request):
    user = request.user
    form = TodoForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = user
        obj.save()
        messages.success(request, 'successfully created')
        return redirect('/')
    return render(request, 'single.html', {'form': form})


def delete(request, pk):
    obj = get_object_or_404(Todo, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.error(request, 'successfully deleted')
        return redirect('/')
    return render(request, 'delete.html', {'obj': obj})

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>ToDo </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' with logo=logo %}
<!--    {% include 'navbar.html' %} -->

    <div class="container">
         <p>{% trans 'Hello' %}</p>
        {% get_current_language as CURRENT_LANGUAGE %}
        {% get_available_languages as AVAILABLE_LANGUAGES %}
        {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
        <div class="languages">
                <p>{% trans "Language" %}:</p>
                <ul class="languages">
                    {% for language in languages %}
                    <li>
                        <a href="/{{ language.code }}/"
                           {% if language.code == CURRENT_LANGUAGE %} class="active" {% endif %}>
                            {{ language.name_local }}
                            <a/>
                    </li>
                {% endfor %}
                </ul>
            </div>
             <div class="messages mt-4 mb-4">
        {% for message in messages %}
            {% if 'success' in message.tags %}

            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
                {% else %}

            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endif %}
        {% endfor %}
    </div>

    {% block content %}

    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <h1>Are  you sure to delete ?</h1>
        <h3>{{ obj.title }}</h3>
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="/" class="btn btn-secondary">Cancel</a>
</form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

        <div class="status-list">
            <a href="?q=0" class="btn btn-primary">{% trans 'New' %}</a>
            <a href="?q=1" class="btn btn-info">Process</a>
            <a href="?q=2" class="btn btn-success">Completed</a>
            <a href="?q=3" class="btn btn-secondary">Cancelled</a>
        </div>

    <div class="todo-card mt-4" >
                {% for todo in todos %}
                <div class="card mt-4">
          <div class="card-header">
               {{ todo.get_status_display }} - <small>last updated: {{ todo.updated_at }}</small>

          </div>
          <div class="card-body">
            <h5 class="card-title">{{ todo.title }}</h5>
            <p class="card-text">{{ todo.content }}</p>
            <a href="/edit/{{ todo.id }}/" class="btn btn-success">Edit</a>
              <a href="/delete/{{ todo.id }}" class="btn btn-danger">Delete</a>

          </div>
          <div class="card-footer text-muted">
            {{ todo.created_at }}
          </div>
</div>
    {% endfor %}
    </div>

{% endblock %}

templates/logout.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sig out?' %}</p>

<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

templates/navbar.html
{% load logo_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
            <img src="{% get_logo %}" alt="error opening picture">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/create/">Add new task</a>
        </li>
      </ul>
        <form class="d-flex">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
                    <li class="nav-item p-2">
                      {{ request.user }}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn bth-light" href="/accounts/logout/">Logout</a>
                    </li>
              {% endif %}
      </ul>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/single.html
{% extends 'base.html' %}

{%  block content %}

    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}